package edu.jhu.cvrg.data.factory.hibernate;

// Generated Dec 7, 2013 2:31:41 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documentrecord generated by hbm2java
 */
@Entity
@Table(name = "documentrecord", schema = "public")
public class DocumentRecord implements java.io.Serializable {

	private static final long serialVersionUID = -5169528861003795811L;
	
	@Id
	@SequenceGenerator(name="documentrecord_sequence",sequenceName="documentrecord_sequence", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="documentrecord_sequence")
	@Column(name = "documentrecordid", unique = true, nullable = false)
	private Long documentRecordId;
	
	@Column(name = "recordname", length = 75)
	private String recordName;
	
	@Column(name = "userid")
	private Long userId;
	
	@Column(name = "subjectid", length = 75)
	private String subjectId;
	
	/** based on the enumeration "fileFormat" in ECGformatCoverter.jar
	 *  
	 * @return
	 */
	@Column(name = "originalformat")
	private Integer originalFormat;
	
	@Column(name = "samplingrate", precision = 17, scale = 17)
	private Double samplingRate;

	@Column(name = "filetreepath", length = 75)
	private String fileTreePath;

	@Column(name = "leadcount")
	private Integer leadCount;
	
	@Column(name = "numberofpoints")
	private Integer numberOfPoints;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateofupload", length = 29)
	private Date dateOfUpload;
	
	@Column(name = "age")
	private Integer age;
	
	@Column(name = "gender", length = 75)
	private String gender;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateofrecording", length = 29)
	private Date dateOfRecording;
	
	@Column(name = "adugain", precision = 17, scale = 17)
	private Double aduGain;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documentRecord", cascade={CascadeType.REMOVE})
	private UploadStatus uploadStatus;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRecord", cascade={CascadeType.REMOVE})
	private Set<AnalysisJob> analysisJobs = new HashSet<AnalysisJob>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRecord", cascade={CascadeType.REMOVE})
	private Set<AnnotationInfo> annotationInfos = new HashSet<AnnotationInfo>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRecord", cascade={CascadeType.REMOVE})
	private List<FileInfo> filesInfo = new ArrayList<FileInfo>(0);

	public DocumentRecord() {
	}

	public DocumentRecord(Long documentrecordid) {
		this.documentRecordId = documentrecordid;
	}

	public DocumentRecord(Long documentrecordid, String recordname,
			Long userid, String subjectid, Integer originalformat,
			Double samplingrate, String filetreepath, Integer leadcount,
			Integer numberofpoints, Date dateofupload, Integer age,
			String gender, Date dateofrecording, Double adugain) {
		this.documentRecordId = documentrecordid;
		this.recordName = recordname;
		this.userId = userid;
		this.subjectId = subjectid;
		this.originalFormat = originalformat;
		this.samplingRate = samplingrate;
		this.fileTreePath = filetreepath;
		this.leadCount = leadcount;
		this.numberOfPoints = numberofpoints;
		this.dateOfUpload = dateofupload;
		this.age = age;
		this.gender = gender;
		this.dateOfRecording = dateofrecording;
		this.aduGain = adugain;
	}

	public Long getDocumentRecordId() {
		return this.documentRecordId;
	}

	public void setDocumentRecordId(Long documentrecordid) {
		this.documentRecordId = documentrecordid;
	}

	public String getRecordName() {
		return this.recordName;
	}

	public void setRecordName(String recordname) {
		this.recordName = recordname;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userid) {
		this.userId = userid;
	}

	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectid) {
		this.subjectId = subjectid;
	}

	public Integer getOriginalFormat() {
		return this.originalFormat;
	}

	public void setOriginalFormat(Integer originalformat) {
		this.originalFormat = originalformat;
	}

	public Double getSamplingRate() {
		return this.samplingRate;
	}

	public void setSamplingRate(Double samplingrate) {
		this.samplingRate = samplingrate;
	}

	public String getFileTreePath() {
		return this.fileTreePath;
	}

	public void setFileTreePath(String filetreepath) {
		this.fileTreePath = filetreepath;
	}

	public Integer getLeadCount() {
		return this.leadCount;
	}

	public void setLeadCount(Integer leadcount) {
		this.leadCount = leadcount;
	}

	public Integer getNumberOfPoints() {
		return this.numberOfPoints;
	}

	public void setNumberOfPoints(Integer numberofpoints) {
		this.numberOfPoints = numberofpoints;
	}

	public Date getDateOfUpload() {
		return this.dateOfUpload;
	}

	public void setDateOfUpload(Date dateofupload) {
		this.dateOfUpload = dateofupload;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDateOfRecording() {
		return this.dateOfRecording;
	}

	public void setDateOfRecording(Date dateofrecording) {
		this.dateOfRecording = dateofrecording;
	}

	public Double getAduGain() {
		return this.aduGain;
	}

	public void setAduGain(Double adugain) {
		this.aduGain = adugain;
	}

	public Set<AnalysisJob> getAnalysisJobs() {
		return this.analysisJobs;
	}

	public void setAnalysisJobs(Set<AnalysisJob> analysisjobs) {
		this.analysisJobs = analysisjobs;
	}

	public UploadStatus getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(UploadStatus uploadstatuses) {
		this.uploadStatus = uploadstatuses;
	}

	public Set<AnnotationInfo> getAnnotationInfos() {
		return this.annotationInfos;
	}

	public void setAnnotationInfos(Set<AnnotationInfo> annotationinfos) {
		this.annotationInfos = annotationinfos;
	}

	public List<FileInfo> getFilesInfo() {
		return this.filesInfo;
	}

	public void setFilesInfo(List<FileInfo> filesinfo) {
		this.filesInfo = filesinfo;
	}

}
